name: overthink_dump
description: A Flutter project for dumping thoughts and insights.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0

  # Charts
  fl_chart: ^0.66.2

  # ðŸ“¸ FOTOÄžRAF + KAMERA
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
